error: use Error::InvalidPath to wrap NulError
Currently, we are not using other types of error such as Utf8Error and
std::io::Error. So we can safely remove them.